version: '3'

services:
  postgres:
    image: postgres:14
    container_name: postgres_breweries
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow_init_breweries
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/app
      - ./jars:/opt/bitnami/spark/jars
    command: >
      bash -c "
        until pg_isready -h ${POSTGRES_HOST} -p ${POSTGRES_PORT}; do
          echo 'Waiting for Postgres...';
          sleep 2;
        done &&
        airflow db migrate &&
        airflow connections create-default-connections &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"

  spark:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: src_breweries
    volumes:
      - ./src:/app
      - ./volumes/warehouse:/warehouse
    depends_on:
      - postgres
    ports:
      - "4040:4040"
    entrypoint: ["sleep", "infinity"]

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow_webserver_breweries
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      PYTHONPATH: /app
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/app
      - ./volumes/warehouse:/warehouse
      - ./requirements.txt:/requirements.txt
      - ./jars:/opt/bitnami/spark/jars
    ports:
      - "8080:8080"
    command: >
      bash -c "
        until pg_isready -h postgres -p 5432; do
          echo 'Waiting for Postgres...';
          sleep 2;
        done &&
        airflow webserver
      "
    depends_on:
      - postgres
      - airflow-init

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow_scheduler_breweries
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      PYTHONPATH: /app
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/app
      - ./volumes/warehouse:/warehouse
      - ./jars:/opt/bitnami/spark/jars
    command: >
      bash -c "
        until pg_isready -h ${POSTGRES_HOST} -p ${POSTGRES_PORT}; do
          echo 'Waiting for Postgres...';
          sleep 2;
        done &&
        airflow scheduler"

volumes:
  pg_data:
