FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN apt-get update && apt-get install -y openjdk-17-jdk
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

COPY src/ src/
COPY tests/ tests/

CMD ["pytest", "--cov=src", "--cov=dags", "--cov-report=term-missing", "-v", "tests"]
